# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-05-14 15:50
from __future__ import unicode_literals

from django.db import migrations



class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.RunSQL(
            sql="""
                CREATE OR REPLACE FUNCTION notify_change() RETURNS TRIGGER AS $$

                    DECLARE
                        data json;
                        notification json;

                    BEGIN
                        IF (TG_OP = 'DELETE') THEN
                            data = row_to_json(OLD);
                        ELSE
                            data = row_to_json(NEW);
                        END IF;

                        notification = json_build_object(
                                          'table',TG_TABLE_NAME,
                                          'action', TG_OP,
                                          'data', data);


                        PERFORM pg_notify('sync',notification::text);

                        -- Result is ignored since this is an AFTER trigger
                        RETURN NULL;
                    END;

                $$ LANGUAGE plpgsql;


                CREATE TRIGGER watched_table_insert
                  AFTER INSERT ON common_syncedthing
                  FOR EACH ROW EXECUTE PROCEDURE notify_change();

                CREATE TRIGGER watched_table_update
                  AFTER UPDATE ON common_syncedthing
                  FOR EACH ROW EXECUTE PROCEDURE notify_change();

                CREATE TRIGGER watched_table_delete
                  AFTER DELETE ON common_syncedthing
                  FOR EACH ROW EXECUTE PROCEDURE notify_change();
            """,
            reverse_sql="""
                DROP TRIGGER watched_table_insert ON common_syncedthing;
                DROP TRIGGER watched_table_update ON common_syncedthing;
                DROP TRIGGER watched_table_delete ON common_syncedthing;
                DROP FUNCTION notify_change();
            """
        ),
    ]
