# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-05-14 15:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.RunSQL(
            sql="""
                CREATE FUNCTION notify_trigger() RETURNS trigger AS $$
                    DECLARE
                    BEGIN
                      PERFORM pg_notify('watchers', TG_TABLE_NAME || ',id,' || NEW.id );
                      RETURN new;
                    END;
                $$ LANGUAGE plpgsql;


                CREATE TRIGGER watched_table_insert
                  AFTER INSERT ON common_syncedthing
                  FOR EACH ROW EXECUTE PROCEDURE notify_trigger();

                CREATE TRIGGER watched_table_update
                  AFTER UPDATE ON common_syncedthing
                  FOR EACH ROW EXECUTE PROCEDURE notify_trigger();

                CREATE TRIGGER watched_table_delete
                  AFTER DELETE ON common_syncedthing
                  FOR EACH ROW EXECUTE PROCEDURE notify_trigger();
            """,
            reverse_sql="""
                DROP TRIGGER watched_table_insert ON common_syncedthing;
                DROP TRIGGER watched_table_update ON common_syncedthing;
                DROP TRIGGER watched_table_delete ON common_syncedthing;
                DROP FUNCTION notify_trigger();
            """
        ),
    ]
